# Generated by Django 2.2 on 2019-04-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('01', 'Deluxe'), ('02', 'Family'), ('03', 'Suite')], max_length=2, null=True),
        ),
    ]
