# Generated by Django 2.2 on 2019-04-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190416_1637'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookingdetail',
            table='booking_detail',
        ),
    ]
