# Generated by Django 2.2 on 2019-04-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20190418_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='num_person',
            field=models.IntegerField(default=1, verbose_name='Person Count'),
        ),
    ]
