# Generated by Django 2.2 on 2019-04-25 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20190418_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_detail', to='booking.Booking'),
        ),
    ]
