# Generated by Django 2.2 on 2019-04-25 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20190425_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='booking.Booking'),
        ),
    ]
