# Generated by Django 2.2 on 2019-04-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20190428_2005'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='bookings',
        ),
    ]
