# Generated by Django 2.2 on 2019-05-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_privilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='booking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking.Booking'),
        ),
        migrations.AlterModelTable(
            name='privilege',
            table='privilege',
        ),
    ]
