# Generated by Django 2.2 on 2019-05-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20190501_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilege',
            name='type',
        ),
        migrations.AddField(
            model_name='privilege',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
