# Generated by Django 2.2 on 2019-05-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20190503_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='booking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booking_detail', to='booking.BookingDetail'),
        ),
    ]
