# Generated by Django 2.2 on 2019-05-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20190503_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stay_date',
        ),
    ]
