# Generated by Django 2.2 on 2019-05-03 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_remove_booking_stay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stay_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='booking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking.Booking'),
        ),
    ]
