# Generated by Django 2.2 on 2019-05-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_auto_20190503_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Used ?'),
        ),
    ]
