# Generated by Django 2.2 on 2019-05-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_auto_20190503_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Unconfirmed'), (1, 'Confirmed'), (2, 'Checked In')], default=0, verbose_name='Booking Status'),
        ),
    ]
