# Generated by Django 2.2 on 2019-05-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Reserved'), (1, 'Checked In'), (2, 'Checked Out')], default=0, verbose_name='Booking Status'),
        ),
    ]
