# Generated by Django 2.2 on 2019-05-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_remove_review_booking'),
        ('booking', '0025_privilege_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.Review'),
        ),
    ]
