# Generated by Django 2.2 on 2019-05-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_booking_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking',
            new_name='review',
        ),
    ]
