# Generated by Django 2.2 on 2019-05-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_auto_20190506_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
