# Generated by Django 2.2 on 2019-05-07 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_bookingdetail_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivilegeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'privilege_type',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'room_type',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Used'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='privilege_type', to='booking.PrivilegeType'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_type', to='booking.RoomType'),
        ),
    ]
