# Generated by Django 2.2.1 on 2019-05-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_auto_20190507_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
    ]
