# Generated by Django 2.2.1 on 2019-05-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_auto_20190507_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Reserved'), (1, 'Checked In'), (2, 'Checked Out'), (3, 'Cancelled')], default=0, verbose_name='Booking Status'),
        ),
    ]
