# Generated by Django 2.2 on 2019-04-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20190418_1652'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
