# Generated by Django 2.2 on 2019-05-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0019_auto_20190503_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('01', 'food'), ('02', 'service')], default='01', max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('detail', models.TextField(null=True)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.BookingDetail')),
                ('service', models.ManyToManyField(to='order.Service')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
