# Generated by Django 2.2 on 2019-05-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('01', 'Food'), ('02', 'Service')], default='01', max_length=255, null=True),
        ),
    ]
