# Generated by Django 2.2 on 2019-04-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190419_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlist',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodlist',
            name='order',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='FoodList',
        ),
    ]
