# Generated by Django 2.2 on 2019-04-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190422_2207'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
    ]
