# Generated by Django 2.2 on 2019-05-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190428_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('01', 'food'), ('02', 'service')], default='01', max_length=255, null=True),
        ),
    ]
